### ISSUE TITLE
Provide examples for new languages

### ISSUE THREAD

**Issue by bzz** [bblfsh/dashboard#119]
_depends on issue https://github.com/bblfsh/dashboard/issues/89 &rarr; PR https://github.com/bblfsh/dashboard/pull/122_

Bblfsh has 6 `recommended` drivers in `beta` state, according to https://doc.bblf.sh/languages.html#supported-languages

Dashboard should catch up and have at least one example of each of those by default.

Thus Golang, Ruby, PHP and JavaScript need to be added.

**Comment by dennwc** [comment]
Might be related to https://github.com/src-d/issues-infrastructure/issues/150

**Comment by dpordomingo** [comment]
it might be also related to https://github.com/bblfsh/dashboard/issues/89

we could reserve some time next week to ensure these three issues have been solved:
- [ ] (a) update server src-d/issues-infrastructure#150
- [ ] (b) provide examples for the new languages bblfsh/dashboard/issues/119 (this one)
- [ ] (c) add new languages to the dropdown bblfsh/dashboard/issues/119 (this one)
- [ ] (d) make the drop-down "dynamic", calling the server to fetch available drivers bblfsh/dashboard/issues/89

(d) could be done separately, or postponed, but once it has been completed, every time a new driver is developed, it would be only needed to do (a); and (b) if it is needed an example for that new language

**Comment by dpordomingo** [comment]
Examples provided by #123
